services:
# user service
  tarantool:
    image: tarantool/tarantool:3
    volumes:
      - ./tarantool_database/init:/opt/tarantool
      - ./tarantool_database/utils:/opt/tarantool/utils
    environment:
      - LUA_PATH=/opt/tarantool/?.lua;/opt/tarantool/?/init.lua
    ports:
      - "3301:3301"
    command: tarantool /opt/tarantool/init.lua
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    environment:
      - DB_HOST=tarantool:3301
    depends_on:
      - tarantool

# AI service
  ai-service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: ai_service_app
    env_file:
      - ai_service/.env
    environment:
      - AUTH_SERVICE_URL=http://user-service:8099/api/v001/auth/check
    ports:
      - "8066:8066"
    restart: unless-stopped
    depends_on:
      - user-service


# Resume storage
  minio-resume-service:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: resume
      MINIO_ROOT_PASSWORD: generator
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres-resume-service:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: generator
      POSTGRES_DB: resume_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./resume_storage/migrate:/docker-entrypoint-initdb.d

  resume-storage:
    build:
      context: .
      dockerfile: ./resume_storage/Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - postgres-resume-service
      - minio-resume-service

volumes:
  minio-storage:
  postgres-data:
