version: '3.8'

services:
  tarantool:
    image: tarantool/tarantool:3
    volumes:
      - ./init:/opt/tarantool
      - ./utils:/opt/tarantool/utils
    environment:
      - LUA_PATH=/opt/tarantool/?.lua;/opt/tarantool/?/init.lua
    ports:
      - "3301:3301"
    command: tarantool /opt/tarantool/init.lua
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  user-service:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    environment:
      - DB_HOST=tarantool:3301
    depends_on:
      - tarantool

  ai-service:
    build:
      context: ../../../ai_service
      dockerfile: dockerfile # Ensure the filename matches
    container_name: ai_service_app
    env_file:
      - ../../../ai_service/.env # Loads all variables from this file
    environment:
      # Removed OPENROUTER_API_KEY line - env_file handles it
      # Ensure AUTH_SERVICE_URL uses the correct service name for the gateway
      - AUTH_SERVICE_URL=http://user-service:8099/api/v001/auth/check
    ports:
      - "8066:8066"
    restart: unless-stopped
    depends_on:
      - user-service
