database:
  user: resume
  password: generator
  name: resume_db
  host: postgres-resume-service:5432

http:
  host: 0.0.0.0
  port: '8100'

object_storage:
  host: minio-resume-service:9000
  user: resume
  password: generator
