definitions:
  models.Education:
    properties:
      degree:
        type: string
      from:
        type: string
      institution:
        type: string
      to:
        type: string
    type: object
  models.Experience:
    properties:
      company:
        type: string
      description:
        type: string
      from:
        type: string
      role:
        type: string
      to:
        type: string
    type: object
  models.SocialProfiles:
    properties:
      linkedin:
        type: string
      telegram:
        type: string
    type: object
  models.User:
    properties:
      id:
        type: integer
      login:
        type: string
      password:
        type: string
    type: object
  models.UserInfo:
    properties:
      education:
        items:
          $ref: '#/definitions/models.Education'
        type: array
      email:
        type: string
      experience:
        items:
          $ref: '#/definitions/models.Experience'
        type: array
      github:
        type: string
      languages:
        items:
          type: string
        type: array
      location:
        type: string
      name:
        type: string
      phone_number:
        type: string
      social_profiles:
        $ref: '#/definitions/models.SocialProfiles'
      surname:
        type: string
      user_id:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8099
info:
  contact: {}
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: User Service API
  version: "1.0"
paths:
  /api/v001/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh tokens.
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: Login successful
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: User login
      tags:
      - Authentication
  /api/v001/auth/logout:
    delete:
      description: Logs out a user by clearing access and refresh tokens.
      responses:
        "200":
          description: Logout successful
          schema:
            type: string
      summary: User logout
      tags:
      - Authentication
  /api/v001/auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user in the system.
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "201":
          description: User registered successfully
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Register a new user
      tags:
      - Authentication
  /api/v001/token:
    get:
      description: Generates a new access token based on the refresh token.
      responses:
        "200":
          description: Access token generated successfully
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Generate access token
      tags:
      - Authentication
  /api/v001/users/info:
    get:
      consumes:
      - application/json
      description: Retrieve a user by its ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User object
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: GetUserInfo a user by ID
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Creates a new user info entry for the authenticated user.
      parameters:
      - description: User info details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new user info
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update an existing user identified by its ID with the provided
        JSON body
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated user object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Update a user by ID
      tags:
      - users
swagger: "2.0"
