name: mkdocs
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - '.github/workflows/mkdocs.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'mkdocs/**'
      - '.github/workflows/mkdocs.yml'
  workflow_dispatch:

jobs:
  build:
    name: Сборка и публикация документации
    runs-on: ubuntu-latest
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions mkdocs-table-reader-plugin

      - name: Сборка MkDocs
        run: |
          cd mkdocs
          mkdocs build

      - name: Деплой на GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mkdocs/site
